export const CDN = "https://res.cloudinary.com/dd9xjzu8c/image/upload"
export const cdnThumb = (id: string) => `${CDN}/q_auto,f_auto,w_800/dmv-garage/${id}`
export const cdnFull = (id: string) => `${CDN}/q_auto,f_auto,w_1920/dmv-garage/${id}`

export type Category = "Sve" | "LED" | "Chiptuning" | "Enterijer" | "Elektronika"
export const categories: Category[] = ["Sve", "LED", "Chiptuning", "Enterijer", "Elektronika"]

export const galleryImages: { id: string; alt: string; category: Category }[] = [
  // LED
  { id: "IMG_0056", alt: "VW Golf cluster – plavi LED", category: "LED" },
  { id: "IMG_0116", alt: "Opel Astra cluster – zeleni LED", category: "LED" },
  { id: "IMG_0432", alt: "Noćni enterijer – LED dashboard", category: "LED" },
  { id: "IMG_0654", alt: "Opel cluster – crveni/plavi LED", category: "LED" },
  { id: "IMG_0881", alt: "BMW cluster – narandžasti LED", category: "LED" },
  { id: "IMG_0884", alt: "BMW cluster – ljubičasti LED", category: "LED" },
  { id: "IMG_0919", alt: "VW Jetta cluster – crveni LED", category: "LED" },
  { id: "IMG_0925", alt: "VW Jetta cluster – plave igle", category: "LED" },
  { id: "IMG_0947", alt: "VW Touran cluster – plavi LED", category: "LED" },
  { id: "IMG_0971", alt: "BMW E46 cluster – plavi LED", category: "LED" },
  { id: "IMG_1075", alt: "VW Golf – plavi paddles + cluster", category: "LED" },
  { id: "IMG_1078", alt: "VW Golf – plavi paddles noć", category: "LED" },
  { id: "IMG_1302", alt: "VW Tiguan cluster – plavi LED", category: "LED" },
  { id: "IMG_1342", alt: "Peugeot cluster – zeleni LED", category: "LED" },
  { id: "IMG_1504", alt: "VW Jetta cluster – plavi LED", category: "LED" },
  { id: "IMG_1507", alt: "VW A3 cluster – plavi LED", category: "LED" },
  { id: "IMG_1540", alt: "Opel Astra radio – plavi LED", category: "LED" },
  { id: "IMG_1544", alt: "Opel Astra cluster – plavi LED", category: "LED" },
  { id: "IMG_1609", alt: "VW cluster – plavi LED", category: "LED" },
  { id: "IMG_1623", alt: "VW Golf cluster – bijeli/plavi LED", category: "LED" },
  { id: "IMG_1624", alt: "VW Golf cluster – plavi LED", category: "LED" },
  { id: "IMG_1654", alt: "VW A3 cluster – plavi LED", category: "LED" },
  { id: "IMG_1671", alt: "Opel Vectra cluster – crveni LED", category: "LED" },
  { id: "IMG_5939", alt: "Skoda cluster – zeleni LED", category: "LED" },
  { id: "IMG_6040", alt: "Audi A6 cluster – plavi LED", category: "LED" },
  { id: "IMG_6093", alt: "BMW E46 cluster – narandžasti LED", category: "LED" },
  { id: "IMG_6096", alt: "BMW E46 cluster – plavi LED", category: "LED" },
  { id: "IMG_6252", alt: "Audi A6 enterijer – crveni LED", category: "LED" },
  { id: "IMG_6311", alt: "Audi A4 cluster – bijeli LED", category: "LED" },
  { id: "IMG_6349", alt: "Enterijer – crveni/plavi LED", category: "LED" },
  { id: "IMG_6459", alt: "VW Passat CC cluster – ljubičasti LED", category: "LED" },
  { id: "IMG_6573", alt: "Peugeot cluster – narandžasti LED", category: "LED" },
  { id: "IMG_6579", alt: "Peugeot cluster – plavi LED", category: "LED" },
  { id: "IMG_6612", alt: "BMW E46 cluster – bijeli LED", category: "LED" },
  { id: "IMG_6758", alt: "BMW cluster – bijeli LED", category: "LED" },
  { id: "IMG_6762", alt: "VW Caddy cluster – crveni/plavi LED", category: "LED" },
  { id: "IMG_6876", alt: "BMW E90 cluster – narandžasti LED", category: "LED" },
  { id: "IMG_6877", alt: "BMW E90 cluster – bijeli LED", category: "LED" },
  { id: "IMG_7168", alt: "Audi A3 cluster – crveni LED", category: "LED" },
  { id: "IMG_7773", alt: "VW cluster – plavi LED", category: "LED" },
  { id: "IMG_7776", alt: "BMW E90 cluster – narandžasti LED", category: "LED" },
  { id: "IMG_7777", alt: "BMW E90 cluster – plavi LED", category: "LED" },
  { id: "IMG_8122", alt: "VW Golf stop svetlo – LED ring crveni", category: "LED" },
  { id: "IMG_8123", alt: "VW Golf stop svetlo – LED ring narandžasti", category: "LED" },
  { id: "IMG_8163", alt: "BMW cluster – plavi LED", category: "LED" },
  { id: "IMG_8360", alt: "BMW F30 klima + radio – plavi LED", category: "LED" },
  { id: "IMG_9868", alt: "VW Golf 6 cluster – plavi LED", category: "LED" },
  { id: "04C8C134-1382-4848-A3D2-D9467CD25DA9", alt: "VW Golf stop svetlo – LED", category: "LED" },
  // Enterijer
  { id: "IMG_1541", alt: "Opel Astra enterijer – plavi LED", category: "Enterijer" },
  { id: "IMG_5947", alt: "BMW E90 – plavo ambijentalno", category: "Enterijer" },
  { id: "IMG_5952", alt: "BMW E90 enterijer – plavi ambijent", category: "Enterijer" },
  { id: "IMG_6306", alt: "Audi Q7 enterijer – crveni LED", category: "Enterijer" },
  { id: "IMG_6308", alt: "Audi Q7 klima – LED", category: "Enterijer" },
  { id: "IMG_7778", alt: "BMW E90 – plavi ambijent + iDrive", category: "Enterijer" },
  { id: "IMG_8358", alt: "BMW F30 – plavi ambijent", category: "Enterijer" },
  { id: "IMG_8361", alt: "BMW F30 enterijer – noćna vožnja", category: "Enterijer" },
  { id: "IMG_8364", alt: "BMW F30 – volan, plavi ambijent", category: "Enterijer" },
  { id: "f5804bcc-0dc9-46a6-aff1-0c4293fb44f5", alt: "Opel Astra OPC – Android + LED", category: "Enterijer" },
  // Elektronika
  { id: "IMG_0051", alt: "VW Golf cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_0113", alt: "Opel Astra cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_0433", alt: "Android multimedija ugradnja", category: "Elektronika" },
  { id: "IMG_0579", alt: "ECU – motorna komora", category: "Elektronika" },
  { id: "IMG_0946", alt: "VW Touran cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_0967", alt: "BMW E46 cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_1124", alt: "BMW E46 cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_1300", alt: "VW Tiguan cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_1341", alt: "Peugeot cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_1515", alt: "Opel Astra cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_1516", alt: "Opel Astra radio – originalni", category: "Elektronika" },
  { id: "IMG_1517", alt: "Opel Astra radio – plavi LED", category: "Elektronika" },
  { id: "IMG_1533", alt: "VW A3 cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_1650", alt: "VW A3 cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_1670", alt: "Opel Vectra cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_5920", alt: "BMW E90 + Android ekran", category: "Elektronika" },
  { id: "IMG_5921", alt: "BMW E90 – stock enterijer", category: "Elektronika" },
  { id: "IMG_5922", alt: "BMW E90 – Android ugradnja", category: "Elektronika" },
  { id: "IMG_5937", alt: "Skoda cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_6034", alt: "Audi A6 cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_6454", alt: "VW Passat CC cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_6650", alt: "Skoda Columbus navigacija", category: "Elektronika" },
  { id: "IMG_6755", alt: "BMW cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_6759", alt: "VW Caddy cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_6760", alt: "JVC radio ugradnja – dnevni prikaz", category: "Elektronika" },
  { id: "IMG_6763", alt: "JVC radio ugradnja – noćni prikaz", category: "Elektronika" },
  { id: "IMG_7164", alt: "Audi A3 cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_7634", alt: "Servis instrument ploče", category: "Elektronika" },
  { id: "IMG_8159", alt: "BMW cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_9860", alt: "VW Golf 6 cluster – dijagnostika", category: "Elektronika" },
  { id: "IMG_9922", alt: "VW cluster – dijagnostika", category: "Elektronika" },
  { id: "copy_44830833-4CDA-456D-AF05-70F5666CC2F1", alt: "Elektronika – servis", category: "Elektronika" },
  // Chiptuning
  { id: "gallery-2", alt: "Chiptuning remap", category: "Chiptuning" },
  { id: "gallery-6", alt: "ECU remap rezultat", category: "Chiptuning" },
  { id: "chiptuning-after", alt: "Chiptuning – rezultat", category: "Chiptuning" },
  { id: "chiptuning-before", alt: "Chiptuning – before", category: "Chiptuning" },
]

const PREVIEW_IDS = [
  "IMG_0654", "IMG_7777", "IMG_8358", "IMG_5920", "IMG_6252",
  "chiptuning-after", "IMG_7778", "IMG_6650", "IMG_6877",
]

const _byId = new Map(galleryImages.map((img) => [img.id, img]))
export const previewImages = PREVIEW_IDS.map((id) => _byId.get(id)).filter(Boolean) as typeof galleryImages
